[profile.release]
lto = true
opt-level = "s"
panic = "abort"

[workspace]
members = [
    "client",
    "curator",
    "indexer",
    "load-balancer",
    "caller-utils",
    "test/demo-test/demo-test"
]
resolver = "2"
